

mod_id=cobblestoney
curse_slug=cobblestoney
curse_id=582368
mod_version=1.0.1
mod_name=cobblestoney
mod_group_id=com.lothrazar.cobblestoney
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=


flib_version=0.1.1
flib_file=8022223
